root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dashboards/choosing-widgets: dashboards/adding-widgets/README.md
  gateways/setting-up-your-gateway: gateways/lorawan-gateways/setting-up-a-lorawan-gateway.md
  gateways/checking-gateway-health: gateways/lorawan-gateways/checking-lorawan-gateway-health.md
  gateways/compatible-gateways: gateways/lorawan-gateways/compatible-lorawan-gateways.md
  dashboards/adding-widgets/image-map-widget: dashboards/adding-widgets/image-widget.md
  settings/data-credits: settings/README.md
